交出 hw1,3,4,5
Lidemy/mentor-program-5th-chachachater pull request #1
Opened 2021-04-14 04:03 UTC by chachachater

hw5 的 第二題，我自己搜尋資料的時候，還是沒辦法很完整的理解瀏覽器接收到 respond 之後的動作是如何 render 出最後的結果

2021-04-16 14:37 UTC, cwc329 requested changes

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +* fork 是複製一個 respository 到本地端
那 `git fork` 還有 `git clone` 有什麼差異？
好像都是複製某個 repo。

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +* 遠端是[GitHub] 和 本地端是[Git] ，它們是各自獨立的，兩者的同步要靠自己的腦袋來記著
真的嗎？
你有用過 `git status` 嗎？
或者有沒有考慮過用華麗的 zsh + zim？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw3.md
> +大部分的人使用電腦的時候，都是使用圖形化的介面來操控電腦，這邊所說的圖形化不只是指圖標、鼠標、陰影、影像那些，而是包括使用者看到的所有畫面，少數例外像是所謂的 Command prompt(或較 terminal)，開啟之後長這樣（Windows 10 為例）↓，可以看到這邊就單只有文字了。
「叫」

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +* fork 是複製一個 respository 到本地端
那 fork 和 clone 有什麼不同？
好像都會複製一個 repo。

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +* 遠端是[GitHub] 和 本地端是[Git] ，它們是各自獨立的，兩者的同步要靠自己的腦袋來記著
真的要靠腦袋記嗎？
如果是這樣為什麼這麼多工程師都在用？
你有用過 `git status` 指令或者用過 zsh + zim 嗎？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +    > 因為是 fork 現有的 respository ，所以就不用 `git init` 了
fork 真的是這個意思嗎？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +    > 注意注意：不要從根目錄 branch，建議 branch 要交作業的資料夾就好 (範例沒有層級之分所以沒有考慮到這點)
開 branch 和 directory 的關係真的是這樣嗎？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +4. 寫作業，寫完之後`git add .` 加到 git stage 裡面，再用 `git commit -m "Is it okay?"`
只要下 `git add .` 就好了嗎？
如果更動過的檔案在上層呢？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +6. 最後再 PR 就可以了↓，完成 commit 之後， Github 部分就完成了
這邊的 commit 又是什麼意思？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +> 作業被改完 = 助教會 merge master，然後把 branch 刪掉
改完不會直接 merge 喔
如果基本要求沒有達到可能會把 PR close 或者要你更新之後再 review 一次。

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw1.md
> +`git pull origin main`
如果刪掉之後發現其實 PR 沒有過要怎麼辦？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw4.md
> +5. 最後來查看版本控制的情況：`git log`
如果不只有笑話 A，而是有好多笑話。
而且同個笑話有很多不同版本要怎麼辦呢？

2021-04-16 14:37 UTC, cwc329 commented on homeworks/week1/hw5.md
> +3. Server 收到 request，經過 database 處理之後送出 respond (HTML, CSS, JS, json, xml ...等)
database 是負責儲存資料的軟體，本身不會處理資料。

2021-04-16 14:43 UTC, cwc329 commented on homeworks/week1/hw5.md
> +
有查資料並且附上來源，這點不對。
推推

2021-04-16 14:46 UTC, cwc329 commented
hw5 寫得不錯，尤其瀏覽器部分寫的滿詳細的，並且有附上資料來源，這點很好。
git 的部分看起來沒有很了解，建議把一些名詞再釐清，最好不要一知半解，不然之後會很辛苦。
hw1 看你想要改了之後再 push 或者 merge 之後再開 branch 訂正都可以。

2021-04-16 17:18 UTC, chachachater commented on homeworks/week1/hw1.md
> +6. 最後再 PR 就可以了↓，完成 commit 之後， Github 部分就完成了
就是在 github 上面的 PR 按 commit

2021-04-16 17:21 UTC, chachachater commented on homeworks/week1/hw1.md
> +`git pull origin main`
再從 PR 那邊下載回來...?

2021-04-17 12:36 UTC, chachachater commented on homeworks/week1/hw4.md
> +5. 最後來查看版本控制的情況：`git log`
在同一個 respository 上面，用不同 branch 來管理

2021-04-17 13:49 UTC, chachachater commented
先 merge ，之後再開 branch 訂正 hw1,3,5

2021-04-17 13:50 UTC, merged